FROM node:20

WORKDIR /app

RUN npm install -g pm2

COPY package*.json ./
COPY packages/adapters-library/package*.json ./packages/adapters-library/
COPY packages/workers/package*.json ./packages/workers/

RUN npm ci

COPY . .

RUN npm run build

CMD ["pm2-runtime", "start", "packages/workers/pm2.config.json"]
