FROM node:20

WORKDIR /app

COPY package*.json ./
COPY packages/adapters-library/package*.json ./packages/adapters-library/
COPY packages/adapters-api/package*.json ./packages/adapters-api/
COPY packages/workers/package*.json ./packages/workers/

RUN npm ci

COPY . .

RUN npm run build

CMD ["node", "packages/adapters-api/index.js"]
