FROM node:20

WORKDIR /app

COPY package*.json ./
COPY packages/adapters-library/package*.json ./packages/adapters-library/
COPY packages/adapters-api/package*.json ./packages/adapters-api/

RUN npm ci

COPY . .

RUN npm run build -w packages/adapters-library
RUN npm run build -w packages/adapters-api

RUN npm prune --production

CMD ["node", "packages/adapters-api/dist/index.js"]
