FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache make g++ python3

COPY package*.json ./
COPY packages/adapters-library/package*.json ./packages/adapters-library/
COPY packages/workers/package*.json ./packages/workers/

RUN npm ci

COPY metadata metadata
COPY packages packages

RUN npm run build -w packages/adapters-library
RUN npm run build -w packages/workers

RUN npm prune --production

CMD ["node", "packages/workers/dist/main.js"]
