FROM node:20

WORKDIR /app

COPY package*.json ./
COPY packages/adapters-library/package*.json ./packages/adapters-library/
COPY packages/dev-backend/package*.json ./packages/dev-backend/
COPY packages/workers/package*.json ./packages/workers/

RUN npm ci

COPY . .

RUN npm run build

CMD ["node", "packages/dev-backend/index.js"]
