/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Cerc20__factory } from "./Cerc20__factory";
export { Comptroller__factory } from "./Comptroller__factory";
