/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TanxFastWithdrawal } from "./TanxFastWithdrawal";
export type { TanxStarkex } from "./TanxStarkex";
export * as factories from "./factories";
export { TanxFastWithdrawal__factory } from "./factories/TanxFastWithdrawal__factory";
export { TanxStarkex__factory } from "./factories/TanxStarkex__factory";
