// eslint-disable-next-line @typescript-eslint/no-explicit-any
const EMPTY_VALUE_FOR_BLANK_ADAPTER_HOOK = '' as any

export const ReplacementPlaceholder = {
  BUILD_METADATA: EMPTY_VALUE_FOR_BLANK_ADAPTER_HOOK,
  GET_PROTOCOL_TOKENS: EMPTY_VALUE_FOR_BLANK_ADAPTER_HOOK,
  GET_POSITIONS: EMPTY_VALUE_FOR_BLANK_ADAPTER_HOOK,
  GET_WITHDRAWALS: EMPTY_VALUE_FOR_BLANK_ADAPTER_HOOK,
  GET_DEPOSITS: EMPTY_VALUE_FOR_BLANK_ADAPTER_HOOK,
  UNWRAP: EMPTY_VALUE_FOR_BLANK_ADAPTER_HOOK,
  ASSET_TYPE: EMPTY_VALUE_FOR_BLANK_ADAPTER_HOOK,
  PRODUCT_ID: EMPTY_VALUE_FOR_BLANK_ADAPTER_HOOK,
  PROTOCOL_ID: EMPTY_VALUE_FOR_BLANK_ADAPTER_HOOK,
  PROTOCOL_KEY: EMPTY_VALUE_FOR_BLANK_ADAPTER_HOOK,
  ADAPTER_CLASS_NAME: EMPTY_VALUE_FOR_BLANK_ADAPTER_HOOK,
  GET_REWARD_POSITIONS: EMPTY_VALUE_FOR_BLANK_ADAPTER_HOOK,
  GET_REWARD_WITHDRAWALS: EMPTY_VALUE_FOR_BLANK_ADAPTER_HOOK,
  IMPLEMENTS_REWARDS_ADAPTER: EMPTY_VALUE_FOR_BLANK_ADAPTER_HOOK,
} as const
