/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export type { OkBitokVault } from './OkBitokVault'
export { OkBitokVault__factory } from './factories/OkBitokVault__factory'
