/* Autogenerated file. Edit at your own risk */
export const Protocol = {
  Stargate: 'stargate',
  AaveV2: 'aave-v2',
  AaveV3: 'aave-v3',
  UniswapV3: 'uniswap-v3',
  Lido: 'lido',
  Curve: 'curve',
  Compound: 'compound',
  Maker: 'maker',
  GMX: 'gmx',
  Swell: 'swell',
  MorphoAaveV2: 'morpho-aave-v2',
  Convex: 'convex',
  Prices: 'prices',
  MorphoCompoundV2: 'morpho-compound-v2',
  MorphoAaveV3ETHOptimizer: 'morpho-aave-v3-eth',
  SyncSwap: 'syncswap',
  IZiSwap: 'iziswap',
  ChimpExchange: 'chimp-exchange',
  MendiFinance: 'mendi-finance',
  MorphoBlue: 'morpho-blue',
} as const
export type Protocol = (typeof Protocol)[keyof typeof Protocol]
