/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common.js";

export interface GaugeSingleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "user_checkpoint"
      | "claimable_tokens"
      | "kick"
      | "set_approve_deposit"
      | "deposit(uint256)"
      | "deposit(uint256,address)"
      | "withdraw"
      | "integrate_checkpoint"
      | "minter"
      | "crv_token"
      | "lp_token"
      | "controller"
      | "voting_escrow"
      | "balanceOf"
      | "totalSupply"
      | "future_epoch_time"
      | "approved_to_deposit"
      | "working_balances"
      | "working_supply"
      | "period"
      | "period_timestamp"
      | "integrate_inv_supply"
      | "integrate_inv_supply_of"
      | "integrate_checkpoint_of"
      | "integrate_fraction"
      | "inflation_rate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Deposit" | "Withdraw" | "UpdateLiquidityLimit"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "user_checkpoint",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimable_tokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "kick", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "set_approve_deposit",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit(uint256,address)",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "integrate_checkpoint",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "minter", values?: undefined): string;
  encodeFunctionData(functionFragment: "crv_token", values?: undefined): string;
  encodeFunctionData(functionFragment: "lp_token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "controller",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "voting_escrow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "future_epoch_time",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approved_to_deposit",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "working_balances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "working_supply",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "period", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "period_timestamp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "integrate_inv_supply",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "integrate_inv_supply_of",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "integrate_checkpoint_of",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "integrate_fraction",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "inflation_rate",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "user_checkpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimable_tokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "kick", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "set_approve_deposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deposit(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deposit(uint256,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "integrate_checkpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "minter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "crv_token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lp_token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "controller", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voting_escrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "future_epoch_time",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approved_to_deposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "working_balances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "working_supply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "period", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "period_timestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "integrate_inv_supply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "integrate_inv_supply_of",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "integrate_checkpoint_of",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "integrate_fraction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inflation_rate",
    data: BytesLike
  ): Result;
}

export namespace DepositEvent {
  export type InputTuple = [provider: AddressLike, value: BigNumberish];
  export type OutputTuple = [provider: string, value: bigint];
  export interface OutputObject {
    provider: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEvent {
  export type InputTuple = [provider: AddressLike, value: BigNumberish];
  export type OutputTuple = [provider: string, value: bigint];
  export interface OutputObject {
    provider: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateLiquidityLimitEvent {
  export type InputTuple = [
    user: AddressLike,
    original_balance: BigNumberish,
    original_supply: BigNumberish,
    working_balance: BigNumberish,
    working_supply: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    original_balance: bigint,
    original_supply: bigint,
    working_balance: bigint,
    working_supply: bigint
  ];
  export interface OutputObject {
    user: string;
    original_balance: bigint;
    original_supply: bigint;
    working_balance: bigint;
    working_supply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GaugeSingle extends BaseContract {
  connect(runner?: ContractRunner | null): GaugeSingle;
  waitForDeployment(): Promise<this>;

  interface: GaugeSingleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  user_checkpoint: TypedContractMethod<
    [addr: AddressLike],
    [boolean],
    "nonpayable"
  >;

  claimable_tokens: TypedContractMethod<
    [addr: AddressLike],
    [bigint],
    "nonpayable"
  >;

  kick: TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;

  set_approve_deposit: TypedContractMethod<
    [addr: AddressLike, can_deposit: boolean],
    [void],
    "nonpayable"
  >;

  "deposit(uint256)": TypedContractMethod<
    [_value: BigNumberish],
    [void],
    "nonpayable"
  >;

  "deposit(uint256,address)": TypedContractMethod<
    [_value: BigNumberish, addr: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[_value: BigNumberish], [void], "nonpayable">;

  integrate_checkpoint: TypedContractMethod<[], [bigint], "view">;

  minter: TypedContractMethod<[], [string], "view">;

  crv_token: TypedContractMethod<[], [string], "view">;

  lp_token: TypedContractMethod<[], [string], "view">;

  controller: TypedContractMethod<[], [string], "view">;

  voting_escrow: TypedContractMethod<[], [string], "view">;

  balanceOf: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  future_epoch_time: TypedContractMethod<[], [bigint], "view">;

  approved_to_deposit: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  working_balances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  working_supply: TypedContractMethod<[], [bigint], "view">;

  period: TypedContractMethod<[], [bigint], "view">;

  period_timestamp: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  integrate_inv_supply: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  integrate_inv_supply_of: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  integrate_checkpoint_of: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  integrate_fraction: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  inflation_rate: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "user_checkpoint"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "claimable_tokens"
  ): TypedContractMethod<[addr: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "kick"
  ): TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "set_approve_deposit"
  ): TypedContractMethod<
    [addr: AddressLike, can_deposit: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit(uint256)"
  ): TypedContractMethod<[_value: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deposit(uint256,address)"
  ): TypedContractMethod<
    [_value: BigNumberish, addr: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[_value: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "integrate_checkpoint"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "crv_token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lp_token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "controller"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "voting_escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "future_epoch_time"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approved_to_deposit"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "working_balances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "working_supply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "period"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "period_timestamp"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "integrate_inv_supply"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "integrate_inv_supply_of"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "integrate_checkpoint_of"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "integrate_fraction"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "inflation_rate"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "Withdraw"
  ): TypedContractEvent<
    WithdrawEvent.InputTuple,
    WithdrawEvent.OutputTuple,
    WithdrawEvent.OutputObject
  >;
  getEvent(
    key: "UpdateLiquidityLimit"
  ): TypedContractEvent<
    UpdateLiquidityLimitEvent.InputTuple,
    UpdateLiquidityLimitEvent.OutputTuple,
    UpdateLiquidityLimitEvent.OutputObject
  >;

  filters: {
    "Deposit(address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "Withdraw(address,uint256)": TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
    Withdraw: TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;

    "UpdateLiquidityLimit(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      UpdateLiquidityLimitEvent.InputTuple,
      UpdateLiquidityLimitEvent.OutputTuple,
      UpdateLiquidityLimitEvent.OutputObject
    >;
    UpdateLiquidityLimit: TypedContractEvent<
      UpdateLiquidityLimitEvent.InputTuple,
      UpdateLiquidityLimitEvent.OutputTuple,
      UpdateLiquidityLimitEvent.OutputObject
    >;
  };
}
