/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stargate from "./stargate";
export type { stargate };
export type { Erc20 } from "./Erc20";
export type { Multicall } from "./Multicall";
export * as factories from "./factories";
export { Erc20__factory } from "./factories/Erc20__factory";
export { Multicall__factory } from "./factories/Multicall__factory";
export type { StargateFactory } from "./stargate/StargateFactory";
export { StargateFactory__factory } from "./factories/stargate/StargateFactory__factory";
export type { StargateToken } from "./stargate/StargateToken";
export { StargateToken__factory } from "./factories/stargate/StargateToken__factory";
export type { StargateVotingEscrow } from "./stargate/StargateVotingEscrow";
export { StargateVotingEscrow__factory } from "./factories/stargate/StargateVotingEscrow__factory";
