/* Autogenerated file. Edit at your own risk */
import { Protocol } from '../../adapters/protocols'
import { Json } from '../../types/json'
import { Chain } from '../constants/chains'

export const MetadataFiles = new Map<string, Json>([])

export function metadataKey({
  protocolId,
  productId,
  chainId,
  fileKey,
}: {
  protocolId: Protocol
  productId: string
  chainId: Chain
  fileKey: string
}) {
  return `${protocolId}.${productId}.${chainId}.${fileKey}`
}
