/* Autogenerated file. Edit at your own risk */
import MorphoBlueMarketBorrowBaseMarketBorrow from '../../adapters/morpho-blue/products/market-borrow/metadata/base.market-borrow.json'
import MorphoBlueMarketBorrowEthereumMarketBorrow from '../../adapters/morpho-blue/products/market-borrow/metadata/ethereum.market-borrow.json'
import MorphoBlueMarketSupplyBaseMarketSupply from '../../adapters/morpho-blue/products/market-supply/metadata/base.market-supply.json'
import MorphoBlueMarketSupplyEthereumMarketSupply from '../../adapters/morpho-blue/products/market-supply/metadata/ethereum.market-supply.json'
import { Protocol } from '../../adapters/protocols'
import { Json } from '../../types/json'
import { Chain } from '../constants/chains'

export const MetadataFiles = new Map<string, Json>([
  [
    metadataKey({
      protocolId: Protocol.MorphoBlue,
      productId: 'market-borrow',
      chainId: Chain.Base,
      fileKey: 'market-borrow',
    }),
    MorphoBlueMarketBorrowBaseMarketBorrow,
  ],
  [
    metadataKey({
      protocolId: Protocol.MorphoBlue,
      productId: 'market-borrow',
      chainId: Chain.Ethereum,
      fileKey: 'market-borrow',
    }),
    MorphoBlueMarketBorrowEthereumMarketBorrow,
  ],
  [
    metadataKey({
      protocolId: Protocol.MorphoBlue,
      productId: 'market-supply',
      chainId: Chain.Base,
      fileKey: 'market-supply',
    }),
    MorphoBlueMarketSupplyBaseMarketSupply,
  ],
  [
    metadataKey({
      protocolId: Protocol.MorphoBlue,
      productId: 'market-supply',
      chainId: Chain.Ethereum,
      fileKey: 'market-supply',
    }),
    MorphoBlueMarketSupplyEthereumMarketSupply,
  ],
])

export function metadataKey({
  protocolId,
  productId,
  chainId,
  fileKey,
}: {
  protocolId: Protocol
  productId: string
  chainId: Chain
  fileKey: string
}) {
  return `${protocolId}.${productId}.${chainId}.${fileKey}`
}
