name: Defiadapters API & Workers - Build and Deploy
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-defiadapters-api-image:
    uses: consensys-vertical-apps/shared-services-workflows/.github/workflows/docker-build-and-validate.yml@v0.61.0
    with:
      github_advanced_security_enabled: true
      trivy_ignore_failure: true
      trivy_skip_db_updates: true
      trivy_skip_java_db_updates: true
      jfrog_auth_enabled: true
      file: Dockerfile.api
      artifact_name: defiadapters-api-build
      artifact_path: defiadapters-api-build.tar

  build-defiadapters-workers-image:
    uses: consensys-vertical-apps/shared-services-workflows/.github/workflows/docker-build-and-validate.yml@v0.61.0
    with:
      github_advanced_security_enabled: true
      trivy_ignore_failure: true
      trivy_skip_db_updates: true
      trivy_skip_java_db_updates: true
      jfrog_auth_enabled: true
      file: Dockerfile.workers
      artifact_name: defiadapters-workers-build
      artifact_path: defiadapters-workers-build.tar

  create-tag:
    uses: consensys-vertical-apps/shared-services-workflows/.github/workflows/create-eph-tag.yml@v0.60.0
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

  deploy-dev-api:
    uses: consensys-vertical-apps/shared-services-workflows/.github/workflows/deploy.yml@v0.60.0
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - build-defiadapters-api-image
      - create-tag
    with:
      environment: dev
      argocd_workload_repository: consensys-vertical-apps/va-mmcx-defiadapters-api-workload
      workload_path: workload/dev/main
      aws_role: arn:aws:iam::024218747365:role/ecr-github-mmcx-dev-defiadapters-api
      aws_region: us-east-2
      ecr_repository: mmcx/dev/defiadapters-api
      image_tag: ${{ needs.create-tag.outputs.tag }}
      artifact_name: defiadapters-api-build
      artifact_path: defiadapters-api-build.tar

    secrets:
      deploy_key: ${{ secrets.DEPLOY_KEY_VA_MMCX_DEFIADAPTERS_API_WORKLOAD }}

  deploy-dev-workers:
    uses: consensys-vertical-apps/shared-services-workflows/.github/workflows/deploy.yml@v0.60.0
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - build-defiadapters-workers-image
      - create-tag
    with:
      environment: dev
      argocd_workload_repository: consensys-vertical-apps/va-mmcx-defiadapters-worker-workload
      workload_path: workload/dev/main
      aws_role: arn:aws:iam::024218747365:role/ecr-github-mmcx-dev-defiadapters-worker
      aws_region: us-east-2
      ecr_repository: mmcx/dev/defiadapters-worker
      image_tag: ${{ needs.create-tag.outputs.tag }}
      artifact_name: defiadapters-workers-build
      artifact_path: defiadapters-workers-build.tar 

    secrets:
      deploy_key: ${{ secrets.DEPLOY_KEY_VA_MMCX_DEFIADAPTERS_WORKER_WORKLOAD }}

  deploy-prd-api:
    uses: consensys-vertical-apps/shared-services-workflows/.github/workflows/deploy.yml@v0.60.0
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - deploy-dev-api
      - create-tag
    with:
      environment: prd
      argocd_workload_repository: consensys-vertical-apps/va-mmcx-defiadapters-api-workload
      workload_path: workload/prd/main
      aws_role: arn:aws:iam::921473456820:role/ecr-github-mmcx-prd-defiadapters-api
      aws_region: us-east-2
      ecr_repository: mmcx/prd/defiadapters-api
      image_tag: ${{ needs.create-tag.outputs.tag }}
      artifact_name: defiadapters-api-build
      artifact_path: defiadapters-api-build.tar
    
    secrets:
      deploy_key: ${{ secrets.DEPLOY_KEY_VA_MMCX_DEFIADAPTERS_API_WORKLOAD }}

  deploy-prd-workers:
    uses: consensys-vertical-apps/shared-services-workflows/.github/workflows/deploy.yml@v0.60.0
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - deploy-dev-workers
      - create-tag
    with:
      environment: prd
      argocd_workload_repository: consensys-vertical-apps/va-mmcx-defiadapters-worker-workload
      workload_path: workload/prd/main
      aws_role: arn:aws:iam::921473456820:role/ecr-github-mmcx-prd-defiadapters-worker
      aws_region: us-east-2
      ecr_repository: mmcx/prd/defiadapters-worker
      image_tag: ${{ needs.create-tag.outputs.tag }}
      artifact_name: defiadapters-workers-build
      artifact_path: defiadapters-workers-build.tar
    
    secrets:
      deploy_key: ${{ secrets.DEPLOY_KEY_VA_MMCX_DEFIADAPTERS_WORKER_WORKLOAD }}
